[theme]
primaryColor = "#ff5c33"
backgroundColor = "#000000"
secondaryBackgroundColor = "#18181b"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
