[theme]
primaryColor = "#ff5c33"
backgroundColor = "#0a0616"
secondaryBackgroundColor = "#1a1726"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
